### Test User Signup
POST http://localhost:3001/signup
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Wayne",
    "email": "john@gmail.com",
    "password": "123484"
}

### Test User Login
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "123456"
}

### Test User Profile
GET http://localhost:3001/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImlhdCI6MTc0MTE4NzczMSwiZXhwIjoxNzQxMTkxMzMxfQ.bGU6QdcndN5qb0FWpp5aQwbd9Ct4tZRT5HFXYbmS_6M

{
    "userId": 4
}

### Test Course Page
GET http://localhost:3001/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImlhdCI6MTc0MTE4NzczMSwiZXhwIjoxNzQxMTkxMzMxfQ.bGU6QdcndN5qb0FWpp5aQwbd9Ct4tZRT5HFXYbmS_6M

### Test Getting a Course
GET http://localhost:3001/courses/Data Structures
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImlhdCI6MTc0MTE4NzczMSwiZXhwIjoxNzQxMTkxMzMxfQ.bGU6QdcndN5qb0FWpp5aQwbd9Ct4tZRT5HFXYbmS_6M

### Creating an admin
