### Test User Signup
POST https://capstone-gmm5.onrender.com/signup
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Wayne",
    "email": "john@gmail.com",
    "password": "123484"
}

### Test User Login
POST https://capstone-gmm5.onrender.com/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "123456"
}

### Test admin login
POST https://capstone-gmm5.onrender.com/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "1234567"
}

### Test User Profile
GET https://capstone-gmm5.onrender.com/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImlhdCI6MTc0MTgwNjg0OCwiZXhwIjoxNzQxODEwNDQ4fQ.Jajys32mMlZ_EBKWrMRHVnmUTLrO6lP7g6J-CgrkF1s

### Test Course Page
GET https://capstone-gmm5.onrender.com/courses
Content-Type: application/json
Authorization: Bearer 

### Test Getting a Course
GET https://capstone-gmm5.onrender.com/courses/Data Structures
Content-Type: application/json
Authorization: Bearer 

### Test Enrolling in a Course
POST https://capstone-gmm5.onrender.com/courses/Data Structures/enroll
Content-Type: application/json
Authorization: Bearer 

### Test Unenrolling in a Course
POST https://capstone-gmm5.onrender.com/courses/Data Structures/unenroll
Content-Type: application/json
Authorization: Bearer 

### Test admin page
GET https://capstone-gmm5.onrender.com/admin
Content-Type: application/json
Authorization: Bearer 

### Test deleting user
DELETE https://capstone-gmm5.onrender.com/admin/users/12
Content-Type: application/json
Authorization: Bearer 

### Test admin creating a user
POST https://capstone-gmm5.onrender.com/admin/users
Content-Type: application/json
Authorization: Bearer 

{
    "firstName": "Michael",
    "lastName": "Scott",
    "email": "michael@gmail.com",
    "password": "123456",
    "admin": "no"
}

### Test admin editing a user
PUT https://capstone-gmm5.onrender.com/admin/users/24
Content-Type: application/json
Authorization: Bearer 

{
    "firstName": "Michael",
    "lastName": "Scotty",
    "email": "michael@gmail.com",
    "password": "123456",
    "admin": "no"
}

### Test User Login
POST https://capstone-gmm5.onrender.com/login
Content-Type: application/json

{
    "email": "michael@gmail.com",
    "password": "123456"
}

### Test user updating profile
PUT https://capstone-gmm5.onrender.com/profile
Content-Type: application/json
Authorization: Bearer 

{
    "firstName": "Michael",
    "lastName": "Scott",
    "email": "michael1@gmail.com"
}

### Test creating a course
POST https://capstone-gmm5.onrender.com/admin/courses
Content-Type: application/json
Authorization: Bearer 

{
    "courseCode": "BIO-101",
    "courseName": "Intro to Evolutionary Science",
    "description": "This course is an introduction to the principles of evolutionary science.",
    "schedule": "MWF 10:00-11:00",
    "room": "Lab-3934",
    "capacity": 30,
    "credits": 3,
    "fee": 100.00
}

### Test editing
PUT https://capstone-gmm5.onrender.com/admin/courses/BIO-101
Content-Type: application/json
Authorization: Bearer 

{
    "courseCode": "BIO-101",
    "courseName": "Intro to Evolutionary Science",
    "description": "This course is an introduction to the principles of evolutionary science.",
    "schedule": "MWF 10:00-11:00",
    "room": "Lab-3934",
    "capacity": 30,
    "credits": 3,
    "fee": 150.00
}

### Test deleting a course
DELETE https://capstone-gmm5.onrender.com/admin/courses/BIO-101
Content-Type: application/json
Authorization: Bearer 

### Test enrolling a user
POST https://capstone-gmm5.onrender.com/admin/users/21/BIO-101/enroll
Content-Type: application/json
Authorization: Bearer 

### Test unenrolling a user
DELETE https://capstone-gmm5.onrender.com/admin/users/21/BIO-101/unenroll
Content-Type: application/json
Authorization: Bearer 
