### Test User Signup
POST http://localhost:3001/signup
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Wayne",
    "email": "john@gmail.com",
    "password": "123484"
}

### Test User Login
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "123456"
}

### Test admin login
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "1234567"
}

### Test User Profile
GET http://localhost:3001/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJlbWFpbCI6Im1pY2hhZWxAZ21haWwuY29tIiwiaWF0IjoxNzQxNzA2NzkyLCJleHAiOjE3NDE3MTAzOTJ9.Az7JlmFAiGkdVVzxFOsrTa_zhQl1bQ5XjLeEOlCHQaw

### Test Course Page
GET http://localhost:3001/courses
Content-Type: application/json
Authorization: Bearer 

### Test Getting a Course
GET http://localhost:3001/courses/Data Structures
Content-Type: application/json
Authorization: Bearer 

### Test Enrolling in a Course
POST http://localhost:3001/courses/Data Structures/enroll
Content-Type: application/json
Authorization: Bearer 

### Test Unenrolling in a Course
POST http://localhost:3001/courses/Data Structures/unenroll
Content-Type: application/json
Authorization: Bearer 

### Test admin page
GET http://localhost:3001/admin
Content-Type: application/json
Authorization: Bearer 

### Test deleting user
DELETE http://localhost:3001/admin/users/12
Content-Type: application/json
Authorization: Bearer 

### Test admin creating a user
POST http://localhost:3001/admin/users
Content-Type: application/json
Authorization: Bearer 

{
    "firstName": "Michael",
    "lastName": "Scott",
    "email": "michael@gmail.com",
    "password": "123456",
    "admin": "no"
}

### Test admin editing a user
PUT http://localhost:3001/admin/users/24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0MTcwMzg5MiwiZXhwIjoxNzQxNzA3NDkyfQ.WAptga-G8FKAaHWP7yumOXfcYe58GSLQiaODh2C_-_I

{
    "firstName": "Michael",
    "lastName": "Scotty",
    "email": "michael@gmail.com",
    "password": "123456",
    "admin": "no"
}

### Test User Login
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "michael@gmail.com",
    "password": "123456"
}


### Test user updating profile
PUT http://localhost:3001/profile
Content-Type: application/json
Authorization: Bearer 

{
    "firstName": "Michael",
    "lastName": "Scott",
    "email": "michael1@gmail.com"
}

### Test creating a course
POST http://localhost:3001/admin/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0MjI1MjU3MCwiZXhwIjoxNzQyMjU2MTcwfQ.3-0jywSyrwOBeI8KJKaNbp1-vg7gM-yMSsATDtJnb7Q

{
    "courseCode": "BIO-1011",
    "courseName": "Intro to Evolutionary Science",
    "description": "This course is an introduction to the principles of evolutionary science.",
    "schedule": "MWF 10:00-11:00",
    "room": "Lab-3934",
    "capacity": 30,
    "credits": 3,
    "fee": 100.00
}

### Test editing
PUT http://localhost:3001/admin/courses/BIO-101
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0MjI1MjU3MCwiZXhwIjoxNzQyMjU2MTcwfQ.3-0jywSyrwOBeI8KJKaNbp1-vg7gM-yMSsATDtJnb7Q

{
    "courseCode": "BIO-101",
    "courseName": "Intro to Evolutionary Science",
    "description": "This course is an introduction to the principles of evolutionary science.",
    "schedule": "MWF 10:00-11:00",
    "room": "Lab-3934",
    "capacity": 30,
    "credits": 3,
    "fee": 150.00
}

### Test deleting a course
DELETE http://localhost:3001/admin/courses/BIO-101
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0MTc5MDAwOSwiZXhwIjoxNzQxNzkzNjA5fQ.eZ6IKooZ1ZhJhYE371JAbqE95EKxdkAjg_vkRX7ykhA

### Test enrolling a user
POST http://localhost:3001/admin/users/21/BIO-101/enroll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0MjI1MjU3MCwiZXhwIjoxNzQyMjU2MTcwfQ.3-0jywSyrwOBeI8KJKaNbp1-vg7gM-yMSsATDtJnb7Q

### Test unenrolling a user
DELETE http://localhost:3001/admin/users/21/BIO-101/unenroll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0MTc5MDgwMSwiZXhwIjoxNzQxNzk0NDAxfQ.XRatboaWV3yJwxd1NjW9d8WPXSaEv7XmFZDeJ40WMjM
